/* AUTO-GENERATED by scripts/build-campaigns.js — edit campaigns.json and run npm run build */
window.PELEPHONE_CAMPAIGN_ROUTES = {
  "/a/": {
    "phoneDisplay": "050-9697015",
    "phoneTel": "0509697015",
    "campaignId": "20355432231",
    "channelName": "pelephone_landing_a",
    "pagePath": "/a/"
  },
  "/b/": {
    "phoneDisplay": "050-1234567",
    "phoneTel": "0501234567",
    "campaignId": "999888777",
    "channelName": "pelephone_landing_b",
    "pagePath": "/b/"
  }
};
