/* AUTO-GENERATED by scripts/build-campaigns.js from pelepone sale page.csv */
window.PELEPHONE_CAMPAIGN_ROUTES = {
  "/": {
    "phoneDisplay": "072-393-1015",
    "phoneTel": "0723931015",
    "campaignId": "8866584363",
    "channelName": "ראשי נייד",
    "pagePath": "/"
  },
  "/a/": {
    "phoneDisplay": "050-9695698",
    "phoneTel": "0509695698",
    "campaignId": "18862440154",
    "channelName": "קבוצה A",
    "pagePath": "/a/"
  },
  "/active/": {
    "phoneDisplay": "050-9695754",
    "phoneTel": "0509695754",
    "campaignId": "12440073323",
    "channelName": "השארת פרטים",
    "pagePath": "/active/"
  },
  "/active-2/": {
    "phoneDisplay": "050-9990472",
    "phoneTel": "0509990472",
    "campaignId": "21582700793",
    "channelName": "השארת פרטים הצטרפות",
    "pagePath": "/active-2/"
  },
  "/am/": {
    "phoneDisplay": "050-9695791",
    "phoneTel": "0509695791",
    "campaignId": "18868006212",
    "channelName": "משותף A",
    "pagePath": "/am/"
  },
  "/b/": {
    "phoneDisplay": "050-9695700",
    "phoneTel": "0509695700",
    "campaignId": "18857864352",
    "channelName": "קבוצה B",
    "pagePath": "/b/"
  },
  "/bm/": {
    "phoneDisplay": "050-9695793",
    "phoneTel": "0509695793",
    "campaignId": "18875105030",
    "channelName": "משותף B",
    "pagePath": "/bm/"
  },
  "/c/": {
    "phoneDisplay": "050-9695723",
    "phoneTel": "0509695723",
    "campaignId": "18857987730",
    "channelName": "קבוצה C",
    "pagePath": "/c/"
  },
  "/cm/": {
    "phoneDisplay": "050-9695805",
    "phoneTel": "0509695805",
    "campaignId": "21583009175",
    "channelName": "משותף C",
    "pagePath": "/cm/"
  },
  "/d/": {
    "phoneDisplay": "050-9695733",
    "phoneTel": "0509695733",
    "campaignId": "18862902919",
    "channelName": "קבוצה D",
    "pagePath": "/d/"
  },
  "/deal/": {
    "phoneDisplay": "050-8308739",
    "phoneTel": "0508308739",
    "campaignId": "8866624275",
    "channelName": "משותף - נייד",
    "pagePath": "/deal/"
  },
  "/desktop/": {
    "phoneDisplay": "050-9695696",
    "phoneTel": "0509695696",
    "campaignId": "18863711270",
    "channelName": "ראשי נייח פלאפון",
    "pagePath": "/desktop/"
  },
  "/e/": {
    "phoneDisplay": "050-9695735",
    "phoneTel": "0509695735",
    "campaignId": "18863405701",
    "channelName": "קבוצה E",
    "pagePath": "/e/"
  },
  "/em/": {
    "phoneDisplay": "050-9697001",
    "phoneTel": "0509697001",
    "campaignId": "18868173543",
    "channelName": "משותף E",
    "pagePath": "/em/"
  },
  "/f/": {
    "phoneDisplay": "050-8308900",
    "phoneTel": "0508308900",
    "campaignId": "21576014079",
    "channelName": "קבוצה F",
    "pagePath": "/f/"
  },
  "/fm/": {
    "phoneDisplay": "050-9695695",
    "phoneTel": "0509695695",
    "campaignId": "21582919373",
    "channelName": "משותף נייח \"פלאפון\"",
    "pagePath": "/fm/"
  },
  "/g/": {
    "phoneDisplay": "050-9997822",
    "phoneTel": "0509997822",
    "campaignId": "21586313728",
    "channelName": "קבוצה G",
    "pagePath": "/g/"
  },
  "/gm/": {
    "phoneDisplay": "050-9697029",
    "phoneTel": "0509697029",
    "campaignId": "21576335673",
    "channelName": "משותף G",
    "pagePath": "/gm/"
  },
  "/h/": {
    "phoneDisplay": "050-9997824",
    "phoneTel": "0509997824",
    "campaignId": "21576107685",
    "channelName": "קבוצה H",
    "pagePath": "/h/"
  },
  "/i/": {
    "phoneDisplay": "050-9997913",
    "phoneTel": "0509997913",
    "campaignId": "21586372537",
    "channelName": "קבוצה I",
    "pagePath": "/i/"
  },
  "/im/": {
    "phoneDisplay": "050-8303611",
    "phoneTel": "0508303611",
    "campaignId": "18874927355",
    "channelName": "משותף נייח חוץ",
    "pagePath": "/im/"
  },
  "/jm/": {
    "phoneDisplay": "050-8307584",
    "phoneTel": "0508307584",
    "campaignId": "18868112373",
    "channelName": "משותף J",
    "pagePath": "/jm/"
  }
};
